name: fuse-fs test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ "main" ]

jobs:

  code_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run integration test
      run: ./integration_test.sh
